import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend, Montserrat } from "next/font/google";
import "./globals.css";
import { AlertModal } from "@/components/common/AlertModal";
import { Footer } from "@/components/common/Footer";
import { Suspense } from "react";
// import localFont from "next/font/local";
import { lexendFontFamily } from "@/lib/utils";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const lexend = lexendFontFamily

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-montserrat antialiased`}
      >
        <Suspense>
          <AlertModal/>
        </Suspense>
        <main className="min-h-[60vh]">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
